-- =============================================================================
-- Stored Procedure: SP_EHRP2BIIS_PRELOAD
-- Migrated from: ehrp2biis_preload (KornShell + Oracle SQL*Plus step01)
-- Original: Orchestration script that calls step01 SQL for staging pre-load
-- =============================================================================

CREATE OR REPLACE PROCEDURE SP_EHRP2BIIS_PRELOAD()
RETURNS VARCHAR
LANGUAGE SQL
EXECUTE AS CALLER
AS
$$
DECLARE
    v_start_ts TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP();
    v_step VARCHAR DEFAULT 'INIT';
    v_row_count INTEGER DEFAULT 0;
BEGIN
    -- ========================================
    -- Step 01: Action Stage Load (pre-load)
    -- Migrated from: step01 / action_stage_load SQL
    -- Original: Called via sqlplus from ehrp2biis_preload shell script
    -- ========================================

    v_step := 'TRUNCATE_STAGING';

    -- Truncate staging tables before new load
    TRUNCATE TABLE IF EXISTS NWK_ACTION_PRIMARY_TBL;
    TRUNCATE TABLE IF EXISTS NWK_ACTION_SECONDARY_TBL;
    TRUNCATE TABLE IF EXISTS NWK_ACTION_REMARKS_TBL;
    TRUNCATE TABLE IF EXISTS NWK_NEW_EHRP_ACTIONS_TBL;

    v_step := 'TRUNCATE_CPM_STAGING';

    -- Truncate CPM staging tables
    TRUNCATE TABLE IF EXISTS CPM_PM1_STG_TBL;
    TRUNCATE TABLE IF EXISTS CPM_PM2_STG_TBL;
    TRUNCATE TABLE IF EXISTS CPM_PM3_STG_TBL;
    TRUNCATE TABLE IF EXISTS CPM_PMH_STG_TBL;
    TRUNCATE TABLE IF EXISTS CPM_YTD_HEADER_STG_TBL;
    TRUNCATE TABLE IF EXISTS CPM_YTD_DETAIL_STG_TBL;
    TRUNCATE TABLE IF EXISTS CPM_YTD_STATE_STG_TBL;
    TRUNCATE TABLE IF EXISTS CPM_MER_HEADER_STG_TBL;
    TRUNCATE TABLE IF EXISTS CPM_MER_DETAIL_STG_TBL;
    TRUNCATE TABLE IF EXISTS CPM_PAD_HEADER_STG_TBL;
    TRUNCATE TABLE IF EXISTS CPM_PAD_DETAIL_STG_TBL;
    TRUNCATE TABLE IF EXISTS CPM_NEWPAY_STG_TYPE_1_2_TBL;
    TRUNCATE TABLE IF EXISTS CPM_NEWPAY_STG_TYPE_3_TBL;
    TRUNCATE TABLE IF EXISTS CPM_NEWPAY_STG_TYPE_3_FDR_TBL;
    TRUNCATE TABLE IF EXISTS CPM_NEWPAY_STG_ALT_TBL;
    TRUNCATE TABLE IF EXISTS CPM_NEWPAY_STG_YTD_STATE_TBL;
    TRUNCATE TABLE IF EXISTS CPM_NEWPAY_STG_DETAIL_TBL;
    TRUNCATE TABLE IF EXISTS CPM_NEWPAY_TBL;
    TRUNCATE TABLE IF EXISTS ERROR_TBL;
    TRUNCATE TABLE IF EXISTS COUNTER_TBL;
    TRUNCATE TABLE IF EXISTS CPM_PAY_PERIOD_DATE_FILE;
    TRUNCATE TABLE IF EXISTS CPM_MESSAGE_FILE;

    v_step := 'COMPLETED';

    RETURN 'SP_EHRP2BIIS_PRELOAD completed successfully at ' || CURRENT_TIMESTAMP()::VARCHAR
        || '. Started: ' || v_start_ts::VARCHAR;

EXCEPTION
    WHEN OTHER THEN
        INSERT INTO ERROR_TBL (PROCESS_NAME, ERROR_MESSAGE, ERROR_DATE)
            VALUES ('SP_EHRP2BIIS_PRELOAD', 'Failed at step ' || v_step || ': ' || SQLERRM, CURRENT_TIMESTAMP());
        RAISE;
END;
$$;
