-- =============================================================================
-- Snowflake Stages & COPY INTO for flat-file (VSAM/CSV) sources
-- Auto-generated from XML/CPM PowerCenter export
-- =============================================================================

USE SCHEMA CPM;

-- Stage for YTD_FILE (source file: PC_DOEYTD_RDF.TXT)
CREATE OR REPLACE STAGE STG_YTD_FILE
  FILE_FORMAT = (TYPE = 'CSV' FIELD_DELIMITER = 'NONE' RECORD_DELIMITER = '\n')
  COMMENT = 'Migrated from Informatica PowerCenter VSAM source: PC_DOEYTD_RDF.TXT';

CREATE TABLE IF NOT EXISTS YTD_FILE_RAW (
    DFAS_YTD_HEADER VARCHAR(1050),
    DFAS_YTD_DETAIL VARCHAR(1129),
    DFAS_YTD_STATE VARCHAR(1052)
);

COPY INTO YTD_FILE_RAW (DFAS_YTD_HEADER, DFAS_YTD_DETAIL, DFAS_YTD_STATE)
  FROM @STG_YTD_FILE
  PATTERN = '.*PC_DOEYTD_RDF[.]TXT.*'
  ON_ERROR = CONTINUE;

-- Stage for MER_FILE (source file: PC_DOEMER_RDF.TXT)
CREATE OR REPLACE STAGE STG_MER_FILE
  FILE_FORMAT = (TYPE = 'CSV' FIELD_DELIMITER = 'NONE' RECORD_DELIMITER = '\n')
  COMMENT = 'Migrated from Informatica PowerCenter VSAM source: PC_DOEMER_RDF.TXT';

CREATE TABLE IF NOT EXISTS MER_FILE_RAW (
    MER_LV_HDR_RECORD VARCHAR(700),
    MER_LV_DETAIL_RECORD VARCHAR(768)
);

COPY INTO MER_FILE_RAW (MER_LV_HDR_RECORD, MER_LV_DETAIL_RECORD)
  FROM @STG_MER_FILE
  PATTERN = '.*PC_DOEMER_RDF[.]TXT.*'
  ON_ERROR = CONTINUE;

-- Stage for PAYMASTER_THREE (source file: PC_DOE_EXP_PMR3.TXT)
CREATE OR REPLACE STAGE STG_PAYMASTER_THREE
  FILE_FORMAT = (TYPE = 'CSV' FIELD_DELIMITER = 'NONE' RECORD_DELIMITER = '\n')
  COMMENT = 'Migrated from Informatica PowerCenter VSAM source: PC_DOE_EXP_PMR3.TXT';

CREATE TABLE IF NOT EXISTS PAYMASTER_THREE_RAW (
    WS_PAY_DETAIL_RECORD VARCHAR(260)
);

COPY INTO PAYMASTER_THREE_RAW (WS_PAY_DETAIL_RECORD)
  FROM @STG_PAYMASTER_THREE
  PATTERN = '.*PC_DOE_EXP_PMR3[.]TXT.*'
  ON_ERROR = CONTINUE;

-- Stage for PAYMASTER_FILE (source file: PC_DOE_EXP_PMR_RDF.TXT)
CREATE OR REPLACE STAGE STG_PAYMASTER_FILE
  FILE_FORMAT = (TYPE = 'CSV' FIELD_DELIMITER = 'NONE' RECORD_DELIMITER = '\n')
  COMMENT = 'Migrated from Informatica PowerCenter VSAM source: PC_DOE_EXP_PMR_RDF.TXT';

CREATE TABLE IF NOT EXISTS PAYMASTER_FILE_RAW (
    WS_PAYMASTER_HEADER VARCHAR(256),
    WS_PAYMASTER_RECORD_1 VARCHAR(258),
    WS_PAYMASTER_RECORD_2 VARCHAR(263),
    WS_PAYMASTER_RECORD_3 VARCHAR(260)
);

COPY INTO PAYMASTER_FILE_RAW (WS_PAYMASTER_HEADER, WS_PAYMASTER_RECORD_1, WS_PAYMASTER_RECORD_2, WS_PAYMASTER_RECORD_3)
  FROM @STG_PAYMASTER_FILE
  PATTERN = '.*PC_DOE_EXP_PMR_RDF[.]TXT.*'
  ON_ERROR = CONTINUE;

-- Stage for PAD_FILE (source file: PC_DOEPAD_RDF.TXT)
CREATE OR REPLACE STAGE STG_PAD_FILE
  FILE_FORMAT = (TYPE = 'CSV' FIELD_DELIMITER = 'NONE' RECORD_DELIMITER = '\n')
  COMMENT = 'Migrated from Informatica PowerCenter VSAM source: PC_DOEPAD_RDF.TXT';

CREATE TABLE IF NOT EXISTS PAD_FILE_RAW (
    PAD_RECORD_HEADER VARCHAR(1400),
    PAD_RECORD_DETAIL VARCHAR(1508)
);

COPY INTO PAD_FILE_RAW (PAD_RECORD_HEADER, PAD_RECORD_DETAIL)
  FROM @STG_PAD_FILE
  PATTERN = '.*PC_DOEPAD_RDF[.]TXT.*'
  ON_ERROR = CONTINUE;
